authors = [
    {
        "id": 1,
        "first_name": "Тарас",
        "last_name": "Шевченко",
        "slug": "taras-shevchenko",
    },
    {"id": 2, "first_name": "Леся", "last_name": "Українка", "slug": "lesya-ukrainka"},
    {"id": 3, "first_name": "Іван", "last_name": "Франко", "slug": "ivan-franko"},
    {
        "id": 4,
        "first_name": "Михайло",
        "last_name": "Коцюбинський",
        "slug": "mykhailo-kotsiubynskyi",
    },
    {
        "id": 5,
        "first_name": "Ольга",
        "last_name": "Кобилянська",
        "slug": "olha-kobylianska",
    },
    {
        "id": 6,
        "first_name": "Валер'ян",
        "last_name": "Підмогильний",
        "slug": "valerian-pidmohylnyi",
    },
    {
        "id": 7,
        "first_name": "Микола",
        "last_name": "Хвильовий",
        "slug": "mykola-khvylovyi",
    },
    {"id": 8, "first_name": "Іван", "last_name": "Багряний", "slug": "ivan-bahrianyi"},
    {"id": 9, "first_name": "Василь", "last_name": "Стус", "slug": "vasyl-stus"},
    {"id": 10, "first_name": "Ліна", "last_name": "Костенко", "slug": "lina-kostenko"},
    {"id": 11, "first_name": "Сергій", "last_name": "Жадан", "slug": "serhiy-zhadan"},
    {
        "id": 12,
        "first_name": "Оксана",
        "last_name": "Забужко",
        "slug": "oksana-zabuzhko",
    },
    {
        "id": 13,
        "first_name": "Юрій",
        "last_name": "Андрухович",
        "slug": "yuriy-andrukhovych",
    },
    {"id": 14, "first_name": "Макс", "last_name": "Кідрук", "slug": "maks-kidruk"},
    {
        "id": 15,
        "first_name": "Ілларіон",
        "last_name": "Павлюк",
        "slug": "illarion-pavliuk",
    },
    {
        "id": 16,
        "first_name": "Андрій",
        "last_name": "Кокотюха",
        "slug": "andriy-kokotiukha",
    },
    {"id": 17, "first_name": "Володимир", "last_name": "Лис", "slug": "volodymyr-lys"},
    {"id": 18, "first_name": "Василь", "last_name": "Шкляр", "slug": "vasyl-shkliar"},
    {"id": 19, "first_name": "Андрій", "last_name": "Курков", "slug": "andriy-kurkov"},
    {"id": 20, "first_name": "Любко", "last_name": "Дереш", "slug": "liubko-deresh"},
    {"id": 21, "first_name": "Артем", "last_name": "Чех", "slug": "artem-chekh"},
    {"id": 22, "first_name": "Артем", "last_name": "Чапай", "slug": "artem-chapai"},
    {
        "id": 23,
        "first_name": "Таня",
        "last_name": "Малярчук",
        "slug": "tanya-malyarchuk",
    },
    {
        "id": 24,
        "first_name": "Софія",
        "last_name": "Андрухович",
        "slug": "sofiya-andrukhovych",
    },
    {
        "id": 25,
        "first_name": "Юрій",
        "last_name": "Винничук",
        "slug": "yuriy-vynnychuk",
    },
    {
        "id": 26,
        "first_name": "Павло",
        "last_name": "Загребельний",
        "slug": "pavlo-zahrebelnyi",
    },
    {
        "id": 27,
        "first_name": "Всеволод",
        "last_name": "Нестайко",
        "slug": "vsevolod-nestaiko",
    },
    {
        "id": 28,
        "first_name": "Григір",
        "last_name": "Тютюнник",
        "slug": "hryhir-tiutiunnyk",
    },
    {
        "id": 29,
        "first_name": "Олександр",
        "last_name": "Довженко",
        "slug": "oleksandr-dovzhenko",
    },
    {"id": 30, "first_name": "Микола", "last_name": "Гоголь", "slug": "mykola-hohol"},
    {
        "id": 31,
        "first_name": "Вільям",
        "last_name": "Шекспір",
        "slug": "william-shakespeare",
    },
    {"id": 32, "first_name": "Джордж", "last_name": "Орвелл", "slug": "george-orwell"},
    {"id": 33, "first_name": "Стівен", "last_name": "Кінг", "slug": "stephen-king"},
    {"id": 34, "first_name": "Джоан", "last_name": "Роулінг", "slug": "j-k-rowling"},
    {"id": 35, "first_name": "Джон", "last_name": "Толкін", "slug": "j-r-r-tolkien"},
    {
        "id": 36,
        "first_name": "Ернест",
        "last_name": "Гемінґвей",
        "slug": "ernest-hemingway",
    },
    {"id": 37, "first_name": "Марк", "last_name": "Твен", "slug": "mark-twain"},
    {
        "id": 38,
        "first_name": "Еріх Марія",
        "last_name": "Ремарк",
        "slug": "erich-maria-remarque",
    },
    {"id": 39, "first_name": "Франц", "last_name": "Кафка", "slug": "franz-kafka"},
    {"id": 40, "first_name": "Альбер", "last_name": "Камю", "slug": "albert-camus"},
    {"id": 41, "first_name": "Рей", "last_name": "Бредбері", "slug": "ray-bradbury"},
    {"id": 42, "first_name": "Агата", "last_name": "Крісті", "slug": "agatha-christie"},
    {
        "id": 43,
        "first_name": "Артур Конан",
        "last_name": "Дойл",
        "slug": "arthur-conan-doyle",
    },
    {
        "id": 44,
        "first_name": "Габріель Гарсія",
        "last_name": "Маркес",
        "slug": "gabriel-garcia-marquez",
    },
    {
        "id": 45,
        "first_name": "Харукі",
        "last_name": "Муракамі",
        "slug": "haruki-murakami",
    },
    {
        "id": 46,
        "first_name": "Джордж",
        "last_name": "Мартін",
        "slug": "george-r-r-martin",
    },
    {"id": 47, "first_name": "Ден", "last_name": "Браун", "slug": "dan-brown"},
    {"id": 48, "first_name": "Ніл", "last_name": "Ґейман", "slug": "neil-gaiman"},
    {
        "id": 49,
        "first_name": "Террі",
        "last_name": " Пратчетт",
        "slug": "terry-pratchett",
    },
    {"id": 50, "first_name": "Айзек", "last_name": "Азімов", "slug": "isaac-asimov"},
    {"id": 51, "first_name": "Філіп", "last_name": "Дік", "slug": "philip-k-dick"},
    {"id": 52, "first_name": "Олдос", "last_name": "Гакслі", "slug": "aldous-huxley"},
    {
        "id": 53,
        "first_name": "Чарльз",
        "last_name": "Діккенс",
        "slug": "charles-dickens",
    },
    {"id": 54, "first_name": "Джейн", "last_name": "Остін", "slug": "jane-austen"},
    {
        "id": 55,
        "first_name": "Шарлотта",
        "last_name": "Бронте",
        "slug": "charlotte-bronte",
    },
    {"id": 56, "first_name": "Віктор", "last_name": "Гюго", "slug": "victor-hugo"},
    {
        "id": 57,
        "first_name": "Александр",
        "last_name": "Дюма",
        "slug": "alexandre-dumas",
    },
    {"id": 58, "first_name": "Жуль", "last_name": "Верн", "slug": "jules-verne"},
    {"id": 59, "first_name": "Джек", "last_name": "Лондон", "slug": "jack-london"},
    {
        "id": 60,
        "first_name": "Едгар Аллан",
        "last_name": "По",
        "slug": "edgar-allan-poe",
    },
    {
        "id": 61,
        "first_name": "Говард",
        "last_name": "Лавкрафт",
        "slug": "h-p-lovecraft",
    },
    {"id": 62, "first_name": "Оскар", "last_name": "Вайльд", "slug": "oscar-wilde"},
    {
        "id": 63,
        "first_name": "Френсіс Скотт",
        "last_name": "Фіцджеральд",
        "slug": "f-scott-fitzgerald",
    },
    {
        "id": 64,
        "first_name": "Клайв Стейплз",
        "last_name": "Льюїс",
        "slug": "c-s-lewis",
    },
    {"id": 65, "first_name": "Ден", "last_name": "Сіммонс", "slug": "dan-simmons"},
    {"id": 66, "first_name": "Френк", "last_name": "Герберт", "slug": "frank-herbert"},
    {"id": 67, "first_name": "Умберто", "last_name": "Еко", "slug": "umberto-eco"},
    {"id": 68, "first_name": "Пауло", "last_name": "Коельйо", "slug": "paulo-coelho"},
    {"id": 69, "first_name": "Мілан", "last_name": "Кундера", "slug": "milan-kundera"},
    {
        "id": 70,
        "first_name": "Кадзуо",
        "last_name": "Ісіґуро",
        "slug": "kazuo-ishiguro",
    },
    {
        "id": 71,
        "first_name": "Юваль Ной",
        "last_name": "Харарі",
        "slug": "yuval-noah-harari",
    },
    {
        "id": 72,
        "first_name": "Джордан",
        "last_name": "Пітерсон",
        "slug": "jordan-peterson",
    },
    {
        "id": 73,
        "first_name": "Деніел",
        "last_name": "Канеман",
        "slug": "daniel-kahneman",
    },
    {
        "id": 74,
        "first_name": "Річард",
        "last_name": "Докінз",
        "slug": "richard-dawkins",
    },
    {
        "id": 75,
        "first_name": "Стівен",
        "last_name": "Гокінг",
        "slug": "stephen-hawking",
    },
    {"id": 76, "first_name": "Метт", "last_name": "Гейґ", "slug": "matt-haig"},
    {
        "id": 77,
        "first_name": "Фредрік",
        "last_name": "Бакман",
        "slug": "fredrik-backman",
    },
    {"id": 78, "first_name": "Джон", "last_name": "Ґрін", "slug": "john-green"},
    {"id": 79, "first_name": "Джуліан", "last_name": "Барнс", "slug": "julian-barnes"},
    {"id": 80, "first_name": "Чак", "last_name": "Поланік", "slug": "chuck-palahniuk"},
    {
        "id": 81,
        "first_name": "Валерій",
        "last_name": "Шевчук",
        "slug": "valeriy-shevchuk",
    },
    {
        "id": 82,
        "first_name": "Григорій",
        "last_name": "Сковорода",
        "slug": "hryhoriy-skovoroda",
    },
    {
        "id": 83,
        "first_name": "Іван",
        "last_name": "Котляревський",
        "slug": "ivan-kotliarevskyi",
    },
    {
        "id": 84,
        "first_name": "Квітка",
        "last_name": "Основ'яненко",
        "slug": "kvitka-osnovianenko",
    },
    {
        "id": 85,
        "first_name": "Пантелеймон",
        "last_name": "Куліш",
        "slug": "panteleimon-kulish",
    },
    {"id": 86, "first_name": "Марко", "last_name": "Вовчок", "slug": "marko-vovchok"},
    {
        "id": 87,
        "first_name": "Іван",
        "last_name": "Нечуй-Левицький",
        "slug": "ivan-nechuy-levytskyi",
    },
    {"id": 88, "first_name": "Панас", "last_name": "Мирний", "slug": "panas-myrnyi"},
    {
        "id": 89,
        "first_name": "Олександр",
        "last_name": "Олесь",
        "slug": "oleksandr-oles",
    },
    {"id": 90, "first_name": "Павло", "last_name": "Тичина", "slug": "pavlo-tychyna"},
    {
        "id": 91,
        "first_name": "Максим",
        "last_name": "Рильський",
        "slug": "maksym-rylskyi",
    },
    {
        "id": 92,
        "first_name": "Володимир",
        "last_name": "Сосюра",
        "slug": "volodymyr-sosiura",
    },
    {"id": 93, "first_name": "Остап", "last_name": "Вишня", "slug": "ostap-vyshnia"},
    {"id": 94, "first_name": "Микола", "last_name": "Куліш", "slug": "mykola-kulish"},
    {
        "id": 95,
        "first_name": "Андрій",
        "last_name": "Малишко",
        "slug": "andriy-malyshko",
    },
    {"id": 96, "first_name": "Олесь", "last_name": "Гончар", "slug": "oles-honchar"},
    {
        "id": 97,
        "first_name": "Дмитро",
        "last_name": "Павличко",
        "slug": "dmytro-pavlychko",
    },
    {
        "id": 98,
        "first_name": "Григорій",
        "last_name": "Тютюнник-Старший",
        "slug": "hryhoriy-tiutiunnyk-senior",
    },
    {
        "id": 99,
        "first_name": "Мирослав",
        "last_name": "Дочинець",
        "slug": "myroslav-dochynets",
    },
    {
        "id": 100,
        "first_name": "Ірен",
        "last_name": "Роздобудько",
        "slug": "iren-rozdobudko",
    },
    {"id": 101, "first_name": "Гомер", "last_name": "", "slug": "homer"},
    {
        "id": 102,
        "first_name": "Данте",
        "last_name": "Аліг'єрі",
        "slug": "dante-alighieri",
    },
    {
        "id": 103,
        "first_name": "Мігель де",
        "last_name": "Сервантес",
        "slug": "miguel-de-cervantes",
    },
    {
        "id": 104,
        "first_name": "Йоганн Вольфганг фон",
        "last_name": "Гете",
        "slug": "johann-wolfgang-von-goethe",
    },
    {
        "id": 105,
        "first_name": "Ганс Крістіан",
        "last_name": "Андерсен",
        "slug": "hans-christian-andersen",
    },
    {
        "id": 106,
        "first_name": "Гі де",
        "last_name": "Мопассан",
        "slug": "guy-de-maupassant",
    },
    {
        "id": 107,
        "first_name": "Генрік",
        "last_name": "Ібсен",
        "slug": "henrik-ibsen",
    },
    {"id": 108, "first_name": "О. Henry", "last_name": "Генрі", "slug": "o-henry"},
    {"id": 109, "first_name": "Томас", "last_name": "Манн", "slug": "thomas-mann"},
    {
        "id": 110,
        "first_name": "Герман",
        "last_name": "Гессе",
        "slug": "hermann-hesse",
    },
    {
        "id": 111,
        "first_name": "Стефан",
        "last_name": "Цвейг",
        "slug": "stefan-zweig",
    },
    {
        "id": 112,
        "first_name": "Марсель",
        "last_name": "Пруст",
        "slug": "marcel-proust",
    },
    {
        "id": 113,
        "first_name": "Джеймс",
        "last_name": "Джойс",
        "slug": "james-joyce",
    },
    {
        "id": 114,
        "first_name": "Вірджинія",
        "last_name": "Вулф",
        "slug": "virginia-woolf",
    },
    {
        "id": 115,
        "first_name": "Вільям",
        "last_name": "Фолкнер",
        "slug": "william-faulkner",
    },
    {
        "id": 116,
        "first_name": "Скотт",
        "last_name": "Векерфельд",
        "slug": "scott-westerfeld",
    },
    {
        "id": 117,
        "first_name": "Антуан де",
        "last_name": "Сент-Екзюпері",
        "slug": "antoine-de-saint-exupery",
    },
    {
        "id": 118,
        "first_name": "Джон",
        "last_name": "Стейнбек",
        "slug": "john-steinbeck",
    },
    {
        "id": 119,
        "first_name": "Джордж",
        "last_name": "Бернард Шоу",
        "slug": "george-bernard-shaw",
    },
    {"id": 120, "first_name": "Брем", "last_name": "Стокер", "slug": "bram-stoker"},
    {"id": 121, "first_name": "Мері", "last_name": "Шеллі", "slug": "mary-shelley"},
    {
        "id": 122,
        "first_name": "Станіслав",
        "last_name": "Лем",
        "slug": "stanislaw-lem",
    },
    {
        "id": 123,
        "first_name": "Януш Леон",
        "last_name": "Вишневський",
        "slug": "janusz-leon-wisniewski",
    },
    {
        "id": 124,
        "first_name": "Ольга",
        "last_name": "Токарчук",
        "slug": "olga-tokarczuk",
    },
    {
        "id": 125,
        "first_name": "Анджей",
        "last_name": "Сапковський",
        "slug": "andrzej-sapkowski",
    },
    {
        "id": 126,
        "first_name": "Ярослав",
        "last_name": "Гашек",
        "slug": "jaroslav-hasek",
    },
    {"id": 127, "first_name": "Алан", "last_name": "Мілн", "slug": "aa-milne"},
    {
        "id": 128,
        "first_name": "Льюїс",
        "last_name": "Керролл",
        "slug": "lewis-carroll",
    },
    {
        "id": 129,
        "first_name": "Астрід",
        "last_name": "Ліндгрен",
        "slug": "astrid-lindgren",
    },
    {
        "id": 130,
        "first_name": "Туве",
        "last_name": "Янссон",
        "slug": "tove-jansson",
    },
    {"id": 131, "first_name": "Роальд", "last_name": "Даль", "slug": "roald-dahl"},
    {"id": 132, "first_name": "Кен", "last_name": "Кізі", "slug": "ken-kesey"},
    {
        "id": 133,
        "first_name": "Курт",
        "last_name": "Воннеґут",
        "slug": "kurt-vonnegut",
    },
    {
        "id": 134,
        "first_name": "Джозеф",
        "last_name": "Геллер",
        "slug": "joseph-heller",
    },
    {
        "id": 135,
        "first_name": "Трумен",
        "last_name": "Капоте",
        "slug": "truman-capote",
    },
    {"id": 136, "first_name": "Харпер", "last_name": "Лі", "slug": "harper-lee"},
    {
        "id": 137,
        "first_name": "Реймонд",
        "last_name": "Чендлер",
        "slug": "raymond-chandler",
    },
    {
        "id": 138,
        "first_name": "Дафна",
        "last_name": "дю Мор'є",
        "slug": "daphne-du-maurier",
    },
    {"id": 139, "first_name": "Айн", "last_name": "Ренд", "slug": "ayn-rand"},
    {
        "id": 140,
        "first_name": "Вільям",
        "last_name": "Голдінг",
        "slug": "william-golding",
    },
    {
        "id": 141,
        "first_name": "Ентоні",
        "last_name": "Берджес",
        "slug": "anthony-burgess",
    },
    {
        "id": 142,
        "first_name": "Уільям",
        "last_name": "Гібсон",
        "slug": "william-gibson",
    },
    {
        "id": 143,
        "first_name": "Дуглас",
        "last_name": "Адамс",
        "slug": "douglas-adams",
    },
    {
        "id": 144,
        "first_name": "Роберт",
        "last_name": "Гайнлайн",
        "slug": "robert-heinlein",
    },
    {
        "id": 145,
        "first_name": "Артур",
        "last_name": "Кларк",
        "slug": "arthur-c-clarke",
    },
    {
        "id": 146,
        "first_name": "Урсула",
        "last_name": "Ле Ґуїн",
        "slug": "ursula-le-guin",
    },
    {"id": 147, "first_name": "Ден", "last_name": "Абнетт", "slug": "dan-abnett"},
    {
        "id": 148,
        "first_name": "Брендон",
        "last_name": "Сандерсон",
        "slug": "brandon-sanderson",
    },
    {
        "id": 149,
        "first_name": "Патрік",
        "last_name": "Ротфусс",
        "slug": "patrick-rothfuss",
    },
    {
        "id": 150,
        "first_name": "Роберт",
        "last_name": "Джордан",
        "slug": "robert-jordan",
    },
    {
        "id": 151,
        "first_name": "Джо",
        "last_name": "Аберкромбі",
        "slug": "joe-abercrombie",
    },
    {"id": 152, "first_name": "Робін", "last_name": "Гобб", "slug": "robin-hobb"},
    {
        "id": 153,
        "first_name": "Маргарет",
        "last_name": "Етвуд",
        "slug": "margaret-atwood",
    },
    {
        "id": 154,
        "first_name": "Джаспер",
        "last_name": "Ффьорде",
        "slug": "jasper-fforde",
    },
    {
        "id": 155,
        "first_name": "Сюзанна",
        "last_name": "Кларк",
        "slug": "susanna-clarke",
    },
    {
        "id": 156,
        "first_name": "Діана Вінн",
        "last_name": "Джонс",
        "slug": "diana-wynne-jones",
    },
    {
        "id": 157,
        "first_name": "Кормак",
        "last_name": "Маккарті",
        "slug": "cormac-mccarthy",
    },
    {
        "id": 158,
        "first_name": "Томас",
        "last_name": "Гарріс",
        "slug": "thomas-harris",
    },
    {
        "id": 159,
        "first_name": "Джеймс",
        "last_name": "Паттерсон",
        "slug": "james-patterson",
    },
    {
        "id": 160,
        "first_name": "Майкл",
        "last_name": "Крайтон",
        "slug": "michael-crichton",
    },
    {
        "id": 161,
        "first_name": "Джон",
        "last_name": "Грішем",
        "slug": "john-grisham",
    },
    {
        "id": 162,
        "first_name": "Девід",
        "last_name": "Балдаччі",
        "slug": "david-baldacci",
    },
    {"id": 163, "first_name": "Лі", "last_name": "Чайлд", "slug": "lee-child"},
    {
        "id": 164,
        "first_name": "Діллан",
        "last_name": "Томас",
        "slug": "dylan-thomas",
    },
    {"id": 165, "first_name": "Ю", "last_name": "Несбьо", "slug": "jo-nesbo"},
    {
        "id": 166,
        "first_name": "Стіг",
        "last_name": "Ларссон",
        "slug": "stieg-larsson",
    },
    {
        "id": 167,
        "first_name": "Хеннінг",
        "last_name": "Манкелль",
        "slug": "henning-mankell",
    },
    {
        "id": 168,
        "first_name": "Гіstandard",
        "last_name": "Флінн",
        "slug": "gillian-flynn",
    },
    {
        "id": 169,
        "first_name": "Пола",
        "last_name": "Гоукінз",
        "slug": "paula-hawkins",
    },
    {
        "id": 170,
        "first_name": "Алекс",
        "last_name": "Міхаелідес",
        "slug": "alex-michaelides",
    },
    {"id": 171, "first_name": "Лю", "last_name": "Цисiнь", "slug": "liu-cixin"},
    {"id": 172, "first_name": "Мо", "last_name": "Янь", "slug": "mo-yan"},
    {
        "id": 173,
        "first_name": "Халед",
        "last_name": "Хоссейні",
        "slug": "khaled-hosseini",
    },
    {"id": 174, "first_name": "Орхан", "last_name": "Памук", "slug": "orhan-pamuk"},
    {"id": 175, "first_name": "Еліф", "last_name": "Шафак", "slug": "elif-shafak"},
    {
        "id": 176,
        "first_name": "Салман",
        "last_name": "Рушді",
        "slug": "salman-rushdie",
    },
    {
        "id": 177,
        "first_name": "Арундаті",
        "last_name": "Рой",
        "slug": "arundhati-roy",
    },
    {
        "id": 178,
        "first_name": "Бернар",
        "last_name": "Вербер",
        "slug": "bernard-werber",
    },
    {"id": 179, "first_name": "Марк", "last_name": "Леві", "slug": "marc-levy"},
    {
        "id": 180,
        "first_name": "Гійом",
        "last_name": "Мюссо",
        "slug": "guillaume-musso",
    },
    {
        "id": 181,
        "first_name": "Фредерік",
        "last_name": "Бегбедер",
        "slug": "frederic-beigbeder",
    },
    {
        "id": 182,
        "first_name": "Анна",
        "last_name": "Гавальда",
        "slug": "anna-gavalda",
    },
    {
        "id": 183,
        "first_name": "Карлос Руїс",
        "last_name": "Сафон",
        "slug": "carlos-ruiz-zafon",
    },
    {
        "id": 184,
        "first_name": "Артуро",
        "last_name": "Перес-Реверте",
        "slug": "arturo-perez-reverte",
    },
    {
        "id": 185,
        "first_name": "Ізабель",
        "last_name": "Альєнде",
        "slug": "isabel-allende",
    },
    {"id": 186, "first_name": "Жоржі", "last_name": "Амаду", "slug": "jorge-amado"},
    {
        "id": 187,
        "first_name": "Маріо Варгас",
        "last_name": "Льоса",
        "slug": "mario-vargas-llosa",
    },
    {
        "id": 188,
        "first_name": "Хорхе Луїс",
        "last_name": "Борхес",
        "slug": "jorge-luis-borges",
    },
    {
        "id": 189,
        "first_name": "Хуліо",
        "last_name": "Кортасар",
        "slug": "julio-cortazar",
    },
    {
        "id": 190,
        "first_name": "Стівен",
        "last_name": "Пінкер",
        "slug": "steven-pinker",
    },
    {
        "id": 191,
        "first_name": "Малколм",
        "last_name": "Гладуелл",
        "slug": "malcolm-gladwell",
    },
    {
        "id": 192,
        "first_name": "Нассім Ніколас",
        "last_name": "Талеб",
        "slug": "nassim-nicholas-taleb",
    },
    {
        "id": 193,
        "first_name": "Джаред",
        "last_name": "Даймонд",
        "slug": "jared-diamond",
    },
    {
        "id": 194,
        "first_name": "Роберт",
        "last_name": "Кійосакі",
        "slug": "robert-kiyosaki",
    },
    {"id": 195, "first_name": "Бодо", "last_name": "Шефер", "slug": "bodo-schafer"},
    {"id": 196, "first_name": "Джеймс", "last_name": "Клір", "slug": "james-clear"},
    {
        "id": 197,
        "first_name": "Саймон",
        "last_name": "Сінек",
        "slug": "simon-sinek",
    },
    {"id": 198, "first_name": "Марк", "last_name": "Менсон", "slug": "mark-manson"},
    {"id": 199, "first_name": "Донна", "last_name": "Тартт", "slug": "donna-tartt"},
    {
        "id": 200,
        "first_name": "Коллін",
        "last_name": "Гівер",
        "slug": "colleen-hoover",
    },
]
