"""Added 'challenge_winners' and 'challenge_super_winners' tables

Revision ID: cc2c2a9dd1ad
Revises: fed93e53c1a1
Create Date: 2026-09-18 21:49:04.439857

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "cc2c2a9dd1ad"
down_revision: Union[str, Sequence[str], None] = "fed93e53c1a1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "challenge_super_winners",
        sa.Column("challenge_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(length=21), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["challenge_id"], ["challenges.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("challenge_id", "user_id"),
    )
    op.create_table(
        "challenge_winners",
        sa.Column("challenge_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(length=21), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["challenge_id"], ["challenges.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("challenge_id", "user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("challenge_winners")
    op.drop_table("challenge_super_winners")
    # ### end Alembic commands ###
