"""Added 'is_spoiler' field into 'book_reviews' table

Revision ID: 8f30bd1bbd94
Revises: c8f17e923d61
Create Date: 2026-08-06 19:20:51.665459

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "8f30bd1bbd94"
down_revision: Union[str, Sequence[str], None] = "c8f17e923d61"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "book_reviews",
        sa.Column("is_spoiler", sa.Boolean(), server_default="0", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("book_reviews", "is_spoiler")
    # ### end Alembic commands ###
