"""Added 'book_selections' and 'book_selection_association' tables

Revision ID: 1a6ac8268da5
Revises: cc2c2a9dd1ad
Create Date: 2026-09-22 19:11:57.448426

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "1a6ac8268da5"
down_revision: Union[str, Sequence[str], None] = "cc2c2a9dd1ad"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "book_selections",
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("author_name", sa.String(length=255), nullable=False),
        sa.Column("cover_image", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="1", nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_book_selections_slug"), "book_selections", ["slug"], unique=True
    )
    op.create_table(
        "book_selection_association",
        sa.Column("book_selection_id", sa.Integer(), nullable=False),
        sa.Column("book_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["book_id"], ["books.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["book_selection_id"], ["book_selections.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("book_selection_id", "book_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("book_selection_association")
    op.drop_index(op.f("ix_book_selections_slug"), table_name="book_selections")
    op.drop_table("book_selections")
    # ### end Alembic commands ###
