"""Added is_important field to book_notes table

Revision ID: 0fd2e3c06ba8
Revises: 2b01a330147a
Create Date: 2026-07-06 19:20:56.415234

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "0fd2e3c06ba8"
down_revision: Union[str, Sequence[str], None] = "2b01a330147a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "book_notes",
        sa.Column("is_important", sa.Boolean(), server_default="0", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("book_notes", "is_important")
    # ### end Alembic commands ###
