"""Added register_way field and changed nullable in password_hash field

Revision ID: 95a06b6e6324
Revises: dd2ea6ee59c7
Create Date: 2026-06-16 20:57:51.198055

"""

from typing import Sequence, Union

from alembic import op
from sqlalchemy.dialects import postgresql
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "95a06b6e6324"
down_revision: Union[str, Sequence[str], None] = "dd2ea6ee59c7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    register_ways_enum = postgresql.ENUM(
        "site", "google", "github", name="register_ways"
    )

    register_ways_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "users",
        sa.Column(
            "register_way",
            sa.Enum("site", "google", "github", name="register_ways"),
            server_default="site",
            nullable=False,
        ),
    )
    op.alter_column("users", "password_hash", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "password_hash", existing_type=sa.VARCHAR(), nullable=False
    )
    op.drop_column("users", "register_way")

    register_ways_enum = postgresql.ENUM("site", "google", name="register_ways")
    register_ways_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
