"""Added 'challenges' table and related it with 'books' and 'users' via 'challenge_books' and 'user_challenges'

Revision ID: c9010a48fbc3
Revises: 4160240d5d6b
Create Date: 2026-09-15 20:01:42.822963

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "c9010a48fbc3"
down_revision: Union[str, Sequence[str], None] = "4160240d5d6b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "challenges",
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("target_count", sa.Integer(), nullable=False),
        sa.Column(
            "challenge_type",
            sa.Enum("book", "comic", "manga", "pages", name="challengetype"),
            server_default="book",
            nullable=False,
        ),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("badge_color", sa.String(length=30), nullable=True),
        sa.Column("sponsor_name", sa.String(length=100), nullable=True),
        sa.Column("publisher_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["publisher_id"], ["book_publishers.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_challenges_slug"), "challenges", ["slug"], unique=True)
    op.create_table(
        "challenge_books",
        sa.Column("challenge_id", sa.Integer(), nullable=False),
        sa.Column("book_id", sa.Integer(), nullable=False),
        sa.Column(
            "added_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(["book_id"], ["books.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["challenge_id"], ["challenges.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("challenge_id", "book_id", "id"),
    )
    op.create_table(
        "user_challenges",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("challenge_id", sa.Integer(), nullable=False),
        sa.Column("current_progress", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("in_progress", "completed", "failed", name="userchallengestatus"),
            server_default="in_progress",
            nullable=False,
        ),
        sa.Column(
            "joined_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(["challenge_id"], ["challenges.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "challenge_id", "id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_challenges")
    op.drop_table("challenge_books")
    op.drop_index(op.f("ix_challenges_slug"), table_name="challenges")
    op.drop_table("challenges")
    # ### end Alembic commands ###
