"""Added 'active' field to 'challenges' table

Revision ID: fed93e53c1a1
Revises: c9010a48fbc3
Create Date: 2026-09-17 19:20:41.821534

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "fed93e53c1a1"
down_revision: Union[str, Sequence[str], None] = "c9010a48fbc3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "challenges",
        sa.Column("active", sa.Boolean(), nullable=True, server_deafult="1"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("challenges", "active")
    # ### end Alembic commands ###
