"""Create social_links model

Revision ID: 6be5bdf0c04a
Revises:
Create Date: 2026-06-01 19:41:11.539764

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "6be5bdf0c04a"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "social_links",
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("link", sa.String(length=100), nullable=False),
        sa.Column("background_color", sa.String(length=7), nullable=True),
        sa.Column("image_src", sa.String(length=50), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("link"),
        sa.UniqueConstraint("title"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("social_links")
    # ### end Alembic commands ###
