"""Added 'min_price' and 'megogo_book_link' fields to 'books' model

Revision ID: 86b9a27b37a8
Revises: 2be526e3b61d
Create Date: 2026-09-23 20:43:34.878560

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "86b9a27b37a8"
down_revision: Union[str, Sequence[str], None] = "2be526e3b61d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("books", sa.Column("min_price", sa.Integer(), nullable=True))
    op.add_column(
        "books",
        sa.Column(
            "megogo_book_link", sa.String(length=255), server_default="", nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("books", "megogo_book_link")
    op.drop_column("books", "min_price")
    # ### end Alembic commands ###
