"""Changed id field in author_book_association table

Revision ID: 36304939e469
Revises: 617da0313646
Create Date: 2026-06-29 20:05:07.137531

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "36304939e469"
down_revision: Union[str, Sequence[str], None] = "617da0313646"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("author_book_association", "id")
    op.drop_column("genre_book_association", "id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "genre_book_association",
        sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "author_book_association",
        sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
