"""Created user_friends table and related it with users

Revision ID: 7354f9f62e9b
Revises: be144bb709cc
Create Date: 2026-07-30 21:27:54.208620

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "7354f9f62e9b"
down_revision: Union[str, Sequence[str], None] = "be144bb709cc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_friends",
        sa.Column("user_id", sa.String(length=21), nullable=False),
        sa.Column("friend_id", sa.String(length=21), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(["friend_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "friend_id", "id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_friends")
    # ### end Alembic commands ###
