"""Added icon field to user_goals table

Revision ID: afc2bab42d26
Revises: 837036c7d348
Create Date: 2026-07-13 21:51:44.120196

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "afc2bab42d26"
down_revision: Union[str, Sequence[str], None] = "837036c7d348"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_goals", sa.Column("icon", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_goals", "icon")
    # ### end Alembic commands ###
