"""Added book_page field to book_notes table

Revision ID: 2256deaf750c
Revises: 0fd2e3c06ba8
Create Date: 2026-07-07 01:15:21.451198

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "2256deaf750c"
down_revision: Union[str, Sequence[str], None] = "0fd2e3c06ba8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("book_notes", sa.Column("book_page", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("book_notes", "book_page")
    # ### end Alembic commands ###
