"""Added 'book_publishers' table and related it with 'books' table

Revision ID: fda548a7c3ad
Revises: 8f30bd1bbd94
Create Date: 2026-08-13 19:06:03.625590

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "fda548a7c3ad"
down_revision: Union[str, Sequence[str], None] = "8f30bd1bbd94"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "book_publishers",
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title"),
    )
    op.add_column("books", sa.Column("isbn", sa.String(length=12), nullable=True))
    op.add_column("books", sa.Column("publisher_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "books", "book_publishers", ["publisher_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "books", type_="foreignkey")
    op.drop_column("books", "publisher_id")
    op.drop_column("books", "isbn")
    op.drop_table("book_publishers")
    # ### end Alembic commands ###
