"""Added user_goals and user_goals_progress tables

Revision ID: 837036c7d348
Revises: 2256deaf750c
Create Date: 2026-07-13 11:42:23.842654

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "837036c7d348"
down_revision: Union[str, Sequence[str], None] = "2256deaf750c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_goals",
        sa.Column("user_id", sa.String(length=21), nullable=False),
        sa.Column("target_value", sa.Integer(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "Сторінки за день",
                "Книги за рік",
                "Книги за місяць",
                "Читацька серія",
                name="usergoalcategory",
            ),
            server_default="Читацька серія",
            nullable=False,
        ),
        sa.Column(
            "period",
            sa.Enum("daily", "monthly", "yearly", "infinite", name="goalperiod"),
            server_default="infinite",
            nullable=False,
        ),
        sa.Column("deadline", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_completed", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_goals_user_id"), "user_goals", ["user_id"], unique=False
    )
    op.create_table(
        "user_goals_progress",
        sa.Column("goal_id", sa.Integer(), nullable=False),
        sa.Column("value", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "log_date", sa.Date(), server_default=sa.text("CURRENT_DATE"), nullable=False
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(["goal_id"], ["user_goals.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_goals_progress_goal_id"),
        "user_goals_progress",
        ["goal_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_goals_progress_log_date"),
        "user_goals_progress",
        ["log_date"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_user_goals_progress_log_date"), table_name="user_goals_progress"
    )
    op.drop_index(
        op.f("ix_user_goals_progress_goal_id"), table_name="user_goals_progress"
    )
    op.drop_table("user_goals_progress")
    op.drop_index(op.f("ix_user_goals_user_id"), table_name="user_goals")
    op.drop_table("user_goals")
    # ### end Alembic commands ###
