"""Added 'session_reactions' table

Revision ID: 4160240d5d6b
Revises: ad64d7cf989d
Create Date: 2026-09-11 20:57:49.078704

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "4160240d5d6b"
down_revision: Union[str, Sequence[str], None] = "ad64d7cf989d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "session_reactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(length=21), nullable=False),
        sa.Column("emoji", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["session_id"], ["reading_sessions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "session_id", "user_id", "emoji", name="uq_session_user_emoji"
        ),
    )
    op.create_index(
        op.f("ix_session_reactions_session_id"),
        "session_reactions",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_session_reactions_user_id"),
        "session_reactions",
        ["user_id"],
        unique=False,
    )
    op.add_column(
        "books", sa.Column("rating", sa.Float(), server_default="0.0", nullable=False)
    )
    op.add_column(
        "books",
        sa.Column("reviews_count", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column("reading_sessions", sa.Column("comment", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reading_sessions", "comment")
    op.drop_column("books", "reviews_count")
    op.drop_column("books", "rating")
    op.drop_index(op.f("ix_session_reactions_user_id"), table_name="session_reactions")
    op.drop_index(
        op.f("ix_session_reactions_session_id"), table_name="session_reactions"
    )
    op.drop_table("session_reactions")
    # ### end Alembic commands ###
