"""Added 'created_at' field into 'book_reviews' table

Revision ID: c8f17e923d61
Revises: 92989e0e6724
Create Date: 2026-08-04 18:36:24.721781

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "c8f17e923d61"
down_revision: Union[str, Sequence[str], None] = "92989e0e6724"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "book_reviews",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("book_reviews", "created_at")
    # ### end Alembic commands ###
