"""Added is_tracked field to reading_sessions table

Revision ID: 16bb024eaeee
Revises: afc2bab42d26
Create Date: 2026-07-16 17:54:20.940162

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "16bb024eaeee"
down_revision: Union[str, Sequence[str], None] = "afc2bab42d26"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "reading_sessions",
        sa.Column("is_tracked", sa.Boolean(), server_default="1", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reading_sessions", "is_tracked")
    # ### end Alembic commands ###
