"""Added 'slug' field to 'book_publishers' table

Revision ID: f867a4a1a224
Revises: fda548a7c3ad
Create Date: 2026-08-17 19:00:01.319472

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "f867a4a1a224"
down_revision: Union[str, Sequence[str], None] = "fda548a7c3ad"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "book_publishers", sa.Column("slug", sa.String(length=255), nullable=False)
    )
    op.create_unique_constraint(None, "book_publishers", ["slug"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "book_publishers", type_="unique")
    op.drop_column("book_publishers", "slug")
    # ### end Alembic commands ###
