"""Added last_read_page in user_book_association table

Revision ID: ef3cdc3b0b3c
Revises: 15f75967e210
Create Date: 2026-08-03 22:14:04.537677

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "ef3cdc3b0b3c"
down_revision: Union[str, Sequence[str], None] = "15f75967e210"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_book_association",
        sa.Column("last_read_page", sa.Integer(), server_default="0", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_book_association", "last_read_page")
    # ### end Alembic commands ###
