"""Added book_notes table and related it with users and book models

Revision ID: 2b01a330147a
Revises: c20b84cf2acc
Create Date: 2026-07-06 15:59:56.417216

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "2b01a330147a"
down_revision: Union[str, Sequence[str], None] = "c20b84cf2acc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "book_notes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(length=21), nullable=False),
        sa.Column("book_id", sa.Integer(), nullable=False),
        sa.Column("note_text", sa.Text(), nullable=False),
        sa.Column(
            "note_category",
            sa.Enum("Думки", "Улюблені цитати", "Підсумки", name="notecategory"),
            server_default="Улюблені цитати",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["book_id"], ["books.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_book_notes_book_id"), "book_notes", ["book_id"], unique=False
    )
    op.create_index(
        op.f("ix_book_notes_user_id"), "book_notes", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_book_notes_user_id"), table_name="book_notes")
    op.drop_index(op.f("ix_book_notes_book_id"), table_name="book_notes")
    op.drop_table("book_notes")
    # ### end Alembic commands ###
