"""Added reading_sessions table and related it with users and books tables

Revision ID: 7af4fa6a2b34
Revises: 9b46286759bf
Create Date: 2026-07-03 11:54:46.995264

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "7af4fa6a2b34"
down_revision: Union[str, Sequence[str], None] = "9b46286759bf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reading_sessions",
        sa.Column("id", sa.String(length=21), nullable=False),
        sa.Column("user_id", sa.String(length=21), nullable=False),
        sa.Column("book_id", sa.Integer(), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("start_page", sa.Integer(), nullable=False),
        sa.Column("end_page", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["book_id"], ["books.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_reading_sessions_book_id"),
        "reading_sessions",
        ["book_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reading_sessions_user_id"),
        "reading_sessions",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_reading_sessions_user_id"), table_name="reading_sessions")
    op.drop_index(op.f("ix_reading_sessions_book_id"), table_name="reading_sessions")
    op.drop_table("reading_sessions")
    # ### end Alembic commands ###
