"""Added 'followers' and 'following' fields to 'users' model

Revision ID: 365fd39cf7a0
Revises: 86b9a27b37a8
Create Date: 2026-10-05 11:27:18.236258

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "365fd39cf7a0"
down_revision: Union[str, Sequence[str], None] = "86b9a27b37a8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_friends",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_friends", "created_at")
    # ### end Alembic commands ###
