"""Create oferta table

Revision ID: 553e65e52eda
Revises: abb48d385b6a
Create Date: 2026-06-04 18:28:52.408164

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "553e65e52eda"
down_revision: Union[str, Sequence[str], None] = "abb48d385b6a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "oferta",
        sa.Column("html_code", sa.Text(), nullable=False),
        sa.Column(
            "last_update",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("oferta")
    # ### end Alembic commands ###
