"""Added unique 'first_name and last name' constraint for 'book_authors' table

Revision ID: ad64d7cf989d
Revises: f867a4a1a224
Create Date: 2026-08-18 21:04:41.959865

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "ad64d7cf989d"
down_revision: Union[str, Sequence[str], None] = "f867a4a1a224"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_book_authors_first_name_last_name",
        "book_authors",
        ["first_name", "last_name"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_book_authors_first_name_last_name", "book_authors", type_="unique"
    )
    # ### end Alembic commands ###
