"""Added 'paused_at' and 'total_paused_duration' fields to 'reading_sessions' table

Revision ID: 9db77008e79e
Revises: 365fd39cf7a0
Create Date: 2026-10-08 21:54:31.071151

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "9db77008e79e"
down_revision: Union[str, Sequence[str], None] = "365fd39cf7a0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "reading_sessions",
        sa.Column("paused_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "reading_sessions",
        sa.Column(
            "total_paused_duration", sa.Integer(), server_default="0", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reading_sessions", "total_paused_duration")
    op.drop_column("reading_sessions", "paused_at")
    # ### end Alembic commands ###
